name: CI with Trivy Scan

on:
  push:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        load: true  # Load the image into Docker environment instead of pushing
        tags: my-php-app:latest

    - name: Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'my-php-app:latest'
        format: 'table'
        output: trivy-report.txt

    - name: Upload Trivy scan results
      uses: actions/upload-artifact@v2
      with:
        name: trivy-report
        path: trivy-report.txt

